services:
  postgres:
    image: postgres:16-alpine
    container_name: hotel_postgres
    environment:
      POSTGRES_DB: hotel_dev_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 03082004
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hotel_network

  redis:
    image: redis:7-alpine
    container_name: hotel_redis
    ports:
      - "56379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hotel_network
    command: redis-server --appendonly yes

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hotel_backend
    env_file:
      - .env
    environment:
      PORT: 4000
      DATABASE_ENV: development
      DATABASE_NAME: hotel_dev_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: 03082004
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      JWT_SECRET: lehoanghuynoob
      DB_LOGGING: false
      NODE_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: redis://redis:6379
      APP_PASS: ${APP_PASS}
      GMAIL_USER: ${GMAIL_USER}
      RESET_PASSWORD_URL: ${RESET_PASSWORD_URL}
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - hotel_network
    command: >
      sh -c "npx sequelize-cli db:migrate && npm run dev"

volumes:
  postgres_data:
  redis_data:

networks:
  hotel_network:
    driver: bridge
