server:
  port: 8081
spring:
  application:
    name: aims

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5433/aims
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      org:
        hibernate:
          envers:
            store_data_at_delete: true
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ieltsonlinetest67@gmail.com
    password: ppzopbjeqwdkximo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  expiration: 2592000
  secret: 2f8925eaa600fb7578d7cfe32c547370e66fb3ac87d79f2ce3a584689f54bb8c

logging:
  level:
    org.springframework: INFO
    org.springframework.security: DEBUG
    com.isd17.aims: DEBUG
    org.hibernate.SQL: DEBUG
    root: INFO

app:
  frontend-url: http://localhost:5173
  shipping:
    free-threshold: 100000
    free-cap: 25000
    inner-base-fee: 22000
    outer-base-fee: 30000
    rush-fee-per-item: 10000
    overweight-fee-per-segment: 2500
    overweight-unit: 0.5
    inner-weight-limit: 3.0
    outer-weight-limit: 0.5

  product:
    delete-per-day: 30
    delete-per-request: 10
    price-change-per-day: 2
    price-value-min-ratio: 0.3
    price-value-max-ratio: 1.5

  payment:
    vat-ratio: 1.1
    vnpay:
      pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
      return-url: http://localhost:5173/payment/payment-callback
      tmn-code: HJHRFWVG
      secret-key: 1BKDBDK2UOBED86C469IHOYNEZ0TUKHH
      api-url: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
      version: 2.1.0
      order-type: other
